---
- name: "Installing additional packages."
  zypper:
    name:
      - bash-completion
      - curl
      - wget
      - git-core
      - net-tools
      - unzip
      - ca-certificates
    state: latest
