---
- name: "Creating a local group for Ansible"
  ansible.builtin.group:
    name: "{{ ANSIBLE_USERNAME }}"

- name: "Creating a local user for Ansible"
  ansible.builtin.user:
    name: "{{ ANSIBLE_USERNAME }}"
    group: "{{ ANSIBLE_USERNAME }}"
    groups: sudo
    password: '!'
    shell: /bin/bash

- name: "Manage authorized_keys for local users"
  ansible.posix.authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.key }}"
  loop:
    - {
      user: "{{ ANSIBLE_USERNAME }}",
      key: "{{ ANSIBLE_SECRET }}"
    }
    - {
      user: "{{ BUILD_USERNAME }}",
      key: "{{ BUILD_SECRET }}"
    }

- name: "Manage sudoers.d for local users"
  community.general.sudoers:
    name: "{{ item }}"
    user: "{{ item }}"
    commands: ALL
  with_items:
    - "{{ ANSIBLE_USERNAME }}"
    - "{{ BUILD_USERNAME }}"
