---
- name: "Adding authorized_keys for the default local user."
  shell: |
    sudo mkdir -p /home/{{BUILD_USERNAME}}/.ssh
    sudo tee /home/{{BUILD_USERNAME}}/.ssh/authorized_keys << EOF
    {{BUILD_KEY}}
    EOF
    sudo chown -R {{BUILD_USERNAME}} /home/{{BUILD_USERNAME}}/.ssh
    sudo chmod 700 /home/{{BUILD_USERNAME}}/.ssh
    sudo chmod 644 /home/{{BUILD_USERNAME}}/.ssh/authorized_keys
- name: "Adding the default local user to passwordless sudoers."
  shell: |
    sudo bash -c "echo \"""{{BUILD_USERNAME}}"" ALL=(ALL) NOPASSWD:ALL\" >> /etc/sudoers"
