---
name: "Code Analysis"
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  code-linting:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: Run GitHub Super-Linter
        uses: github/super-linter@45fc0d88288beee4701c62761281edfee85655d7 # v5.0.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          DEFAULT_BRANCH: "develop"
          DISABLE_ERRORS: false
          FILTER_REGEX_EXCLUDE: "build.tmpl"
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          DOCKERFILE_HADOLINT_FILE_NAME: .hadolint.yml
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_NATURAL_LANGUAGE: true
          VALIDATE_POWERSHELL: true
          VALIDATE_TERRAFORM_FMT: true
          VALIDATE_TERRAFORM_TFLINT: true
          VALIDATE_YAML: true
          YAML_CONFIG_FILE: .yamllint.yml
