---
name: Manage Stale Items
on:
  schedule:
    - cron: 00 00 * * *
jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@1160a2240286f5da8ec72b1c0816ce2481aabf84 # v8.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          days-before-stale: 60
          days-before-close: 30
          exempt-issue-labels: "status/needs-triage, status/planned"
          exempt-pr-labels: "status/needs-review, status/planned"
          remove-stale-when-updated: true
          delete-branch: false
          stale-issue-label: status/stale
          stale-issue-message: >-
            Marking this issue as stale due to inactivity. This helps us focus
            on the active issues. If this issue receives no comments in the next
            30 days it will automatically be closed.


            If this issue was automatically closed and you feel this issue
            should be reopened, we encourage creating a new issue linking back
            to this one for added context. Thank you!
          stale-pr-label: status/stale
          stale-pr-message: >-
            Marking this pull request as stale due to inactivity. This helps us
            focus on the active pull requests. If this pull request receives no
            comments in the next 30 days it will automatically be closed.


            If this pull request was automatically closed and you feel this pull
            request should be reopened, we encourage creating a new pull request
            linking back to this one for added context. Thank you!
