# https://github.com/actions/stale
name: Manage stale issues and pull requests

on:
  schedule:
  - cron: '15 22 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 60
        days-before-close: 30
        exempt-issue-labels: 'needs-triage, in-progress'
        exempt-pr-labels: 'needs-review, under-review, planned'
        remove-stale-when-updated: true
        labels-to-remove-when-unstale: stale
        delete-branch: false
        stale-issue-label: stale
        stale-issue-message: |
            Marking this issue as stale due to inactivity. This helps us focus on the active issues. If this issue receives no comments in the next 30 days it will automatically be closed.
            If this issue was automatically closed and you feel this issue should be reopened, we encourage creating a new issue linking back to this one for added context. Thank you!
        stale-pr-label: 'stale'
        stale-pr-message: |
            Marking this pull request as stale due to inactivity. This helps us focus on the active pull requests. If this pull request receives no comments in the next 30 days it will automatically be closed.
            If this pull request was automatically closed and you feel this pull request should be reopened, we encourage creating a new pull request linking back to this one for added context. Thank you!

